name: Generate Nim Docsets

on:
  workflow_dispatch:
    inputs:
      nim-version:
        description: "The version of nim to generate the documentation for, it can be a semver, a branch or commit hash"
        required: false
        default: "nightly:https://github.com/nim-lang/nightlies/releases/tag/2024-06-25-devel-2c83f94544b9acc6d06fd6b7fcf035e5cb0aa8eb"

permissions:
  contents: write

jobs:
  build-nim-docsets:
    name: Generate Nim ${{ inputs.nim-version }} Docsets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install nim ${{inputs.nim-version}}"
        uses: iffy/install-nim@v5
        with:
          version: ${{ inputs.nim-version }}

      - uses: actions/setup-go@v5

      - name: "Generate docset"
        uses: melMass/actions@nukit
        id: generate
        with:
          script: |
            go install github.com/technosophos/dashing@latest
            nim e docset.nims --version

            let version = (nim --version | lines | first | parse -r '(\d+\.\d+\.\d+)' | first | rename DOCSET_VERSION) 
            print $version

            $version | to-github

            let docset = (ls *docset.zip | get name | first | path expand | {NIM_DOCSET:$in})
            print $docset
            $docset | to-github

      - name: ✅ Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nim_${{ env.DOCSET_VERSION }}_docsets
          name: "Nim ${{ env.DOCSET_VERSION }} Docsets"
          body: "Generated docsets for Nim ${{ env.DOCSET_VERSION }}."
          draft: false
          prerelease: false
          files: |
            ${{env.NIM_DOCSET}}
